version: "3.8"

services:
  frontend:
    build:
      context: frontend
      dockerfile: ../Dockerfile
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - frontend-backend
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      dockerfile: ../Dockerfile
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
    networks:
      - backend-database
      - frontend-backend
    expose:
      - 3000
    environment:
      - MONGO_URL=mongodb://database:27017/TodoApp
    stdin_open: true
    command: nodemon server.js

  database:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - backend-database
    expose:
      - 27017

networks:
  frontend-backend:
  backend-database:
