name: Deploy to Railway

on:
  push:
    branches:
      - todo-replica

jobs:
  tangle-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Install Railway CLI
      run: curl -fsSL cli.new | sh
    - name: Install Emacs
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt-get update
        sudo apt-get install -y emacs28
    - uses: actions/checkout@v2
    - name: Tangle Org mode file
      run: |
        emacs --batch --eval "(progn (find-file \"README.org\") (org-babel-tangle))"
    - name: Commit tangled code
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -f *
        git commit -m "Tangled code"
        git push
    - name: Deploy
      run: |
        ls -la
        railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
