name: Deploy to Railway

on:
  push:
    branches:
      - todo-replica

jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Railway CLI
      run: curl -fsSL cli.new | sh
    - name: Install Emacs
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt-get update
        sudo apt-get install -y emacs28
    - name: Tangling Org mode file
      run: |
        emacs --batch --eval "(progn (find-file \"README.org\") (org-babel-tangle))"
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
