name: Tangle code

on:
  push:
    branches:
      - todo-replica

jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
    - name: Install Emacs
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt-get update
        sudo apt-get install -y emacs28
    - uses: actions/checkout@v2
    - name: Tangle README.org
      run: |
        emacs --batch --eval "(progn (find-file \"README.org\") (org-babel-tangle))"
    - name: Commit tangled code
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b tangled
        git add -f *
        git commit -m "Tangled code"
        git push --force --set-upstream origin tangled
