name: Tangling Org Mode File

on:
  push:
    branches:
      - todo-replica

jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Emacs and Org mode
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs
    - name: Tangling Org mode file
      run: |
        emacs --batch --eval "(progn (find-file \"README.org\") (org-babel-tangle))"
	ls -la
