name: Tangle code
on:
  push:
    branches:
      - main
jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
      - name: Install Emacs
        run: |
          sudo add-apt-repository ppa:kelleyk/emacs
          sudo apt-get update
          sudo apt-get install -y emacs28
      - name: Check out main
        uses: actions/checkout@v3
      - name: Tangle README.org
        run: emacs --batch --eval "(progn (find-file \"README.org\") (org-babel-tangle))"
      - name: Check out tangled
        uses: actions/checkout@v3
        with:
          ref: tangled
