name: Tangle code
on:
  push:
    branches:
      - main
jobs:
  update-branch-tangled:
    runs-on: ubuntu-latest
    steps:
      - name: Install Emacs
        run: |
          sudo add-apt-repository ppa:kelleyk/emacs
          sudo apt-get update
          sudo apt-get install -y emacs28
      - name: Check out main
        uses: actions/checkout@v3
      - name: Tangle README.org
        run: emacs --batch --eval "(progn (find-file \"README.org\") (org-babel-tangle))"
      - name: Add, commit and push to tangled
        run: |
          mv -f .gitignore-tangled .gitignore
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git fetch origin
          git checkout -B origin/tangled
          git add .
          git commit -m "Tangled code"
          git push --force tangled
